export const TOTAL_ATTEMPTS = 8;

export const data = {
  movies: {
    name: 'Movies',
    words: [
      'The Godfather',
      'Titanic',
      'Inception',
      'Gladiator',
      'Casablanca',
      'Psycho',
      'Avatar',
      'Jaws',
      'Frozen',
      'The Matrix',
      'Goodfellas',
      'Braveheart',
      'Fight Club',
      'Pulp Fiction',
      'Forrest Gump',
      'The Lion King',
      'Jurassic Park',
      'Blade Runner',
      'Star Wars',
      'The Dark Knight',
      'The Big Lebowski',
      'Toy Story',
      'Alien',
      'Interstellar',
      'La La Land',
    ],
  },
  'tv-shows': {
    name: 'TV Shows',
    words: [
      'Breaking Bad',
      'South Park',
      'Game of Thrones',
      'Stranger Things',
      'The Sopranos',
      'Friends',
      'The Office',
      'Sherlock',
      'Black Mirror',
      'The Crown',
      'Westworld',
      'Better Call Saul',
      'The Simpsons',
      'Arrested Development',
      'Succession',
      'Fargo',
      'Mad Men',
      'The West Wing',
      'Dexter',
      'Rick and Morty',
      'Lost',
      'Doctor Who',
      'The Walking Dead',
      'Peaky Blinders',
      'Curb Your Enthusiasm',
      'Ted Lasso',
      'True Detective',
    ],
  },
  countries: {
    name: 'Countries',
    words: [
      'Australia',
      'Brazil',
      'Canada',
      'Denmark',
      'Egypt',
      'France',
      'Germany',
      'Hungary',
      'India',
      'Japan',
      'Kenya',
      'Luxembourg',
      'Mexico',
      'Netherlands',
      'Oman',
      'Peru',
      'Qatar',
      'Russia',
      'Spain',
      'Thailand',
      'United Kingdom',
      'Vietnam',
      'Italy',
      'United States',
      'China',
      'South Africa',
      'New Zealand',
      'Argentina',
      'Belgium',
      'Chile',
    ],
  },
  'capital-cities': {
    name: 'Capital Cities',
    words: [
      'Tokyo',
      'Paris',
      'London',
      'Kuala Lumpur',
      'Berlin',
      'Ottawa',
      'Canberra',
      'Moscow',
      'Beijing',
      'New Delhi',
      'Copenhagen',
      'Cairo',
      'Madrid',
      'Rome',
      'Buenos Aires',
      'Bangkok',
      'Vienna',
      'Seoul',
      'Jakarta',
      'Lisbon',
      'Riyadh',
      'Helsinki',
      'Oslo',
      'Stockholm',
      'Athens',
      'Dublin',
      'Prague',
      'Budapest',
      'Warsaw',
      'Amsterdam',
    ],
  },
  animals: {
    name: 'Animals',
    words: [
      'Elephant',
      'Lion',
      'Giraffe',
      'Penguin',
      'Dolphin',
      'Tiger',
      'Kangaroo',
      'Panda',
      'Zebra',
      'Polar Bear',
      'Cheetah',
      'Rhino',
      'Buffalo',
      'Koala',
      'Gorilla',
      'Chimpanzee',
      'Crocodile',
      'Flamingo',
      'Peacock',
      'Jaguar',
      'Leopard',
      'Wolf',
      'Fox',
      'Bald Eagle',
      'Owl',
      'Frog',
      'Shark',
      'Octopus',
      'Turtle',
      'Snake',
    ],
  },
  sports: {
    name: 'Sports',
    words: [
      'Soccer',
      'Basketball',
      'Tennis',
      'Baseball',
      'Rock Climbing',
      'Swimming',
      'Volleyball',
      'Table Tennis',
      'Badminton',
      'Rugby',
      'Cricket',
      'Hockey',
      'Boxing',
      'Martial Arts',
      'Fencing',
      'Archery',
      'Skiing',
      'Bobsleigh',
      'Cycling',
      'Curling',
      'Surfing',
      'Diving',
      'Gymnastics',
      'Athletics',
      'Rowing',
      'Sailing',
      'Canoeing',
      'Ice Hockey',
      'Triathlon',
      'American Football',
    ],
  },
};
